name: todays first pipeline
on:
  push:
    branch: [ main ]

jobs:
  test: 
    runs-on: ubuntu-latest
    
    steps: 
       - name: bring the code
         run: actions/checkout@v3

       - name: node setup karo ubuntu pe
         uses: actions/setup-node@v3
         with: 
             node-versio: "18"

      - name: package.json install karo
        run: npm install

      - name: Tests chalao
        run: npm test

